# vars/main.yml

services:
  - name: plausible
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible-postgres
      - plausible-events
      - plausible-geoip
    env_file:
      - ./plausible.env
    volumes:
      - ./data/geoip/GeoLite2-Country.mmdb:/plausible/geoip/GeoLite2-Country.mmdb
      - ./data/geoip/geonames.csv:/plausible/geoip/geonames.csv
      - ./data/geoip/GeoLite2-City.mmdb:/plausible/geoip/GeoLite2-City.mmdb
    networks:
      - plausible
    traefik:
      - name: plausible
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: public-chain@file
        insecuretransport: false
        service_port: 8000
      - name: plausible_admin
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`) && PathPrefix(`/login`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 8000
    watchtower: true

  - name: plausible-postgres
    image: postgres:13
    env_file:
      - ./plausible-postgres.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - plausible
    watchtower: true

  - name: plausible-events
    image: clickhouse/clickhouse-server:latest-alpine
    user: "{{ common_uid }}:{{ common_gid }}"
    volumes:
      - ./data/events/data:/var/lib/clickhouse
      - ./data/events/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./data/events/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - plausible
    watchtower: true

  - name: plausible-geoip
    image: maxmindinc/geoipupdate:latest
    env_file:
      - ./plausible-geoip.env
    volumes:
      - ./data/geoip:/usr/share/GeoIP
      - ./data/GeoIP.conf:/etc/GeoIP.conf
    networks:
      - plausible
    watchtower: true